version: '3'

services:
  eureka-server:
    image: fjunqueira/spring-cloud-playground-eureka-server
    ports:
      - 8010:8010
    networks:
      - spring-cloud-bridge-network

  eureka-client:
    image: fjunqueira/spring-cloud-playground-eureka-client
    networks:
      - spring-cloud-bridge-network
    depends_on:
      - eureka-server

  hystrix-client:
    image: fjunqueira/spring-cloud-playground-hystrix-client
    networks:
      - spring-cloud-bridge-network
    depends_on:
      - eureka-server
      - eureka-client

  zull-gateway-api:
    image: fjunqueira/spring-cloud-playground-zuul-gateway-api
    ports:
      - 8080:8080
    networks:
      - spring-cloud-bridge-network
    depends_on:
      - eureka-server
      - eureka-client
      - hystrix-client

networks:
  spring-cloud-bridge-network:
    driver: bridge
