spring:
  profiles: default
  application:
    name: hystrix-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
server:
  port: 8040


# allow Actuator to expose the Hystrix stream
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream