---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8010  
eureka:
  instance:
    hostname: eureka-host
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: us-east-1
  application:
    name: eureka-server
server:
  port: 8011  
eureka:
  instance:
    hostname: server-us-east-1       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://server-us-west-1:8012/eureka/,http://server-ap-south-1:8013/eureka/

---
spring:
  profiles: us-west-1
  application:
    name: eureka-server
server:
  port: 8012
eureka:
  instance:
    hostname: server-us-west-1       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://server-ap-south-1:8013/eureka/,http://server-us-east-1:8011/eureka/

---
spring:
  profiles: ap-south-1
  application:
    name: eureka-server
server:
  port: 8013
eureka:
  instance:
    hostname: server-ap-south-1       
  client:
    registerWithEureka: true
    fetchRegistry: true    
    serviceUrl:
      defaultZone: http://server-us-east-1:8011/eureka/,http://server-us-west-1:8012/eureka/      